(ns mtg-sdk.models.card-test
  (:use [clojure.test])
  (:require [clojure.data.json :as json]
            [schema.core :as s]
            [mtg-sdk.models :refer [Card]]))

(deftest card-test
  (let [valid-json-card (str "{\"name\":\"Narnam Cobra\",\"manaCost\":\"{2}\","
                             "\"cmc\":2,\"colorIdentity\":[\"G\"],\"type\":"
                             "\"Artifact Creature \u2014 Snake\",\"types\":"
                             "[\"Artifact\",\"Creature\"],\"subtypes\":"
                             "[\"Snake\"],\"rarity\":\"Common\",\"set\":"
                             "\"KLD\",\"setName\":\"Kaladesh\",\"text\":"
                             "\"{G}: Narnam Cobra gains deathtouch until end "
                             "of turn. (Any amount of damage it deals to a "
                             "creature is enough to destroy it.)\",\"flavor\""
                             ":\"Some say tales of the Narnam greenhouse are "
                             "told to scare the children, but every tale "
                             "grows from a seed of truth.\",\"artist\":"
                             "\"Christopher Burdett\",\"number\":\"224\","
                             "\"power\":\"2\",\"toughness\":\"1\",\"layout\":"
                             "\"normal\",\"multiverseid\":417797,\"imageUrl\""
                             ":\"http:\\/\\/gatherer.wizards.com\\/Handlers"
                             "\\/Image.ashx?multiverseid=417797&type=card\","
                             "\"foreignNames\":[{\"name\":\"\u7EB3\u5357\u773C"
                             "\u955C\u86C7\",\"imageUrl\":\"http:\\/\\/gatherer."
                             "wizards.com\\/Handlers\\/Image.ashx?multiverseid="
                             "418061&type=card\",\"language\":\"Chinese "
                             "Simplified\",\"multiverseid\":418061},{\"name\":"
                             "\"\u7D0D\u5357\u773C\u93E1\u86C7\",\"imageUrl\":"
                             "\"http:\\/\\/gatherer.wizards.com\\/Handlers\\/Image."
                             "ashx?multiverseid=418325&type=card\",\"language\""
                             ":\"Chinese Traditional\",\"multiverseid\":418325}"
                             ",{\"name\":\"Cobra de Narnam\",\"imageUrl\":"
                             "\"http:\\/\\/gatherer.wizards.com\\/Handlers\\/Image."
                             "ashx?multiverseid=418853&type=card\",\"language\":"
                             "\"French\",\"multiverseid\":418853},{\"name\":"
                             "\"Narnam-Kobra\",\"imageUrl\":\"http:\\/\\/gatherer."
                             "wizards.com\\/Handlers\\/Image.ashx?multiverseid="
                             "418589&type=card\",\"language\":\"German\","
                             "\"multiverseid\":418589},{\"name\":\"Cobra di "
                             "Narnam\",\"imageUrl\":\"http:\\/\\/gatherer.wizards."
                             "com\\/Handlers\\/Image.ashx?multiverseid=419117&"
                             "type=card\",\"language\":\"Italian\",\"multiverseid\""
                             ":419117},{\"name\":\"\u30CA\u30FC\u30CA\u30E0"
                             "\u306E\u30B3\u30D6\u30E9\",\"imageUrl\":"
                             "\"http:\\/\\/gatherer.wizards.com\\/Handlers\\/Image."
                             "ashx?multiverseid=419381&type=card\",\"language\""
                             ":\"Japanese\",\"multiverseid\":419381},{\"name\":"
                             "\"\uB098\uB974\uB0A8 \uCF54\uBE0C\uB77C\","
                             "\"imageUrl\":\"http:\\/\\/gatherer.wizards.com"
                             "\\/Handlers\\/Image.ashx?multiverseid=419645&type="
                             "card\",\"language\":\"Korean\",\"multiverseid\":"
                             "419645},{\"name\":\"Naja da Narnam\",\"imageUrl\""
                             ":\"http:\\/\\/gatherer.wizards.com\\/Handlers\\/Image."
                             "ashx?multiverseid=419909&type=card\",\"language\":"
                             "\"Portuguese (Brazil)\",\"multiverseid\":419909},"
                             "{\"name\":\"\u041D\u0430\u0440\u043D\u0430\u043C"
                             "\u0441\u043A\u0430\u044F \u041A\u043E\u0431\u0440"
                             "\u0430\",\"imageUrl\":\"http:\\/\\/gatherer.wizards"
                             ".com\\/Handlers\\/Image.ashx?multiverseid=420173&"
                             "type=card\",\"language\":\"Russian\",\"multiverseid\""
                             ":420173},{\"name\":\"Cobra de Narnam\",\"imageUrl\""
                             ":\"http:\\/\\/gatherer.wizards.com\\/Handlers\\/Image."
                             "ashx?multiverseid=420437&type=card\",\"language\":"
                             "\"Spanish\",\"multiverseid\":420437}],\"printings\":"
                             "[\"KLD\"],\"originalText\":\"{G}: Narnam Cobra "
                             "gains deathtouch until end of turn. (Any amount "
                             "of damage it deals to a creature is enough to "
                             "destroy it.)\",\"originalType\":\"Artifact "
                             "Creature \u2014 Snake\",\"legalities\":[{\"format\""
                             ":\"Commander\",\"legality\":\"Legal\"},{\"format\":"
                             "\"Kaladesh Block\",\"legality\":\"Legal\"},"
                             "{\"format\":\"Legacy\",\"legality\":\"Legal\"},"
                             "{\"format\":\"Modern\",\"legality\":\"Legal\"},"
                             "{\"format\":\"Standard\",\"legality\":\"Legal\"},"
                             "{\"format\":\"Vintage\",\"legality\":\"Legal\"}],"
                             "\"id\":\"940788fd95ff81af51cbb0897440d2c26f34646b\"}")
        valid-card (json/read-str valid-json-card :key-fn keyword)]
    (testing "valid card is valid"
      (is (s/validate Card valid-card)))))
